on:
  push:
    branches: [dev]
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: ec2 ssh login
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            whoami
            ls -al
      #         cd /home/ubuntu/projects/crawling && docker-compose up -d
      # - name: Build docker_
      #   run: |
      #     docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      #     echo ${{ secrets.DOCKERHUB_TOKEN }}
    #       docker buildx create --use
    #       docker buildx build --platform linux/amd64,linux/arm64/v8 -t devleekiseok0126/nestjs-crawl:dev --push
