on:
  push:
    branches: [dev]
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t devleekiseok0126/nestjs-crawl:dev . --push

  deploy-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - name: ec2 ssh login
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            whoami
            ls -al
            cd /home/ubuntu/projects/crawling
            docker stop dev-app
            docker rm dev-app
            docker-compose up -d
